// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKny9R-g2W5cBF4R5frtA3UIJ6M0iVmdw',
    appId: '1:99228179064:web:234377b32bfe978ab5ab8d',
    messagingSenderId: '99228179064',
    projectId: 'qanoni-app',
    authDomain: 'qanoni-app.firebaseapp.com',
    storageBucket: 'qanoni-app.appspot.com',
    measurementId: 'G-V78G9F5ZYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdYAu2zTvv0rJ3c0VTOAX02e1TiWzoYw',
    appId: '1:99228179064:android:20c2680ef07ae54db5ab8d',
    messagingSenderId: '99228179064',
    projectId: 'qanoni-app',
    storageBucket: 'qanoni-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCex0_zeKuuLv2-yGRDh9m50Nb3E1IOAUs',
    appId: '1:99228179064:ios:3bb05ab001e63431b5ab8d',
    messagingSenderId: '99228179064',
    projectId: 'qanoni-app',
    storageBucket: 'qanoni-app.appspot.com',
    iosBundleId: 'com.example.qanoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCex0_zeKuuLv2-yGRDh9m50Nb3E1IOAUs',
    appId: '1:99228179064:ios:3bb05ab001e63431b5ab8d',
    messagingSenderId: '99228179064',
    projectId: 'qanoni-app',
    storageBucket: 'qanoni-app.appspot.com',
    iosBundleId: 'com.example.qanoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKny9R-g2W5cBF4R5frtA3UIJ6M0iVmdw',
    appId: '1:99228179064:web:349dbefe20a126cbb5ab8d',
    messagingSenderId: '99228179064',
    projectId: 'qanoni-app',
    authDomain: 'qanoni-app.firebaseapp.com',
    storageBucket: 'qanoni-app.appspot.com',
    measurementId: 'G-1751G85YTJ',
  );
}
